### PR TITLE
Pathing

### PR DESCRIPTION
**Pull request by mooomooo**
This adds A* path planning to find an optimal route to a desired destination point, especially useful in maps with lots of obstacles / walls so you don't have to manually navigate around.  The example map was added as alxcc (Alexandria Code & Coffee), with the appropriate features on layer 0.

### CODE REVIEW

**Comment by mooomooo** [comment]
Incidentally, I added the logic to Game.moveMeBy, but it can go in the pointerup event handler if it behaves poorly with keypresses.

**Comment by capnmidnight** [comment]
This sounds awesome. Would you do me one favor and move `astar.js` from the `src` directory to the `lib` directory, please? I'll check it out tomorrow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mooomooo** [comment]
Moved.  I also made it only apply when clicking because weird things were happening with keypresses.

**Comment by capnmidnight** [comment]
This is out now with v0.2.0

**Pull request merged**
